"""Training entrypoint: run full training with real-time logs and curve plotting."""

import json
import sys
from pathlib import Path
from typing import Dict, List

import matplotlib.pyplot as plt
import numpy as np

PROJECT_ROOT = Path(__file__).resolve().parent.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from src.config import DATA_PREP, PATHS, TRAIN
from src.models.mlp import MLPConfig, ThreeLayerMLP
from src.training.optimizer import SGD, SGDConfig
from src.training.trainer import Trainer


def load_preprocessed_splits() -> Dict[str, np.ndarray]:
    """Load train/val/test arrays from outputs/*.npz generated by prepare_data.py."""
    split_path = PATHS.outputs_dir / f"{DATA_PREP.file_prefix}.npz"
    if not split_path.exists():
        raise FileNotFoundError(
            f"Split file not found: {split_path}. Run scripts/prepare_data.py first."
        )

    data = np.load(split_path)
    required = ("x_train", "y_train", "x_val", "y_val", "x_test", "y_test")
    for key in required:
        if key not in data:
            raise KeyError(f"Missing key in split file: {key}")

    return {
        "x_train": data["x_train"],
        "y_train": data["y_train"],
        "x_val": data["x_val"],
        "y_val": data["y_val"],
        "x_test": data["x_test"],
        "y_test": data["y_test"],
    }


def build_model(input_dim: int, output_dim: int) -> ThreeLayerMLP:
    """Build MLP from central config. input_dim/output_dim are inferred from data."""
    mlp_cfg = MLPConfig(
        input_dim=input_dim,
        hidden_dim1=TRAIN.hidden_dim1,
        hidden_dim2=TRAIN.hidden_dim2,
        output_dim=output_dim,
        activation=TRAIN.activation,
    )
    return ThreeLayerMLP(mlp_cfg, seed=TRAIN.seed)


def plot_training_curves(history: Dict[str, List[float]], output_dir: Path) -> None:
    """Save loss and validation accuracy curves under outputs/figures."""
    output_dir.mkdir(parents=True, exist_ok=True)
    epochs = np.arange(1, len(history["train_loss"]) + 1)

    # Loss curves: train + val
    plt.figure(figsize=(8, 5))
    plt.plot(epochs, history["train_loss"], label="Train Loss", linewidth=2)
    plt.plot(epochs, history["val_loss"], label="Validation Loss", linewidth=2)
    plt.xlabel("Epoch")
    plt.ylabel("Loss")
    plt.title("Training and Validation Loss")
    plt.grid(True, alpha=0.3)
    plt.legend()
    plt.tight_layout()
    loss_path = output_dir / "loss_curve.png"
    plt.savefig(loss_path, dpi=150)
    plt.close()

    # Validation accuracy curve
    plt.figure(figsize=(8, 5))
    plt.plot(epochs, history["val_acc"], label="Validation Accuracy", linewidth=2)
    plt.xlabel("Epoch")
    plt.ylabel("Accuracy")
    plt.title("Validation Accuracy")
    plt.grid(True, alpha=0.3)
    plt.legend()
    plt.tight_layout()
    acc_path = output_dir / "val_accuracy_curve.png"
    plt.savefig(acc_path, dpi=150)
    plt.close()

    print(f"Saved loss curve: {loss_path}")
    print(f"Saved val accuracy curve: {acc_path}")


def save_history(history: Dict[str, List[float]], output_dir: Path) -> Path:
    """Save training history as JSON for reproducibility/reporting."""
    output_dir.mkdir(parents=True, exist_ok=True)
    history_path = output_dir / "train_history.json"
    history_path.write_text(json.dumps(history, indent=2), encoding="utf-8")
    return history_path


def main() -> None:
    print("[Train] Loading preprocessed data...")
    split = load_preprocessed_splits()

    x_train = split["x_train"]
    y_train = split["y_train"]
    x_val = split["x_val"]
    y_val = split["y_val"]

    inferred_input_dim = int(x_train.shape[1])
    inferred_output_dim = int(np.max(y_train) + 1)

    print(
        f"[Train] Data loaded. train={x_train.shape}, val={x_val.shape}, "
        f"inferred_input_dim={inferred_input_dim}, inferred_output_dim={inferred_output_dim}"
    )

    model = build_model(input_dim=inferred_input_dim, output_dim=inferred_output_dim)
    optimizer = SGD(
        SGDConfig(
            learning_rate=TRAIN.learning_rate,
            lr_decay_gamma=TRAIN.lr_decay_gamma,
        )
    )

    trainer = Trainer(
        model=model,
        optimizer=optimizer,
        x_train=x_train,
        y_train=y_train,
        x_val=x_val,
        y_val=y_val,
        epochs=TRAIN.epochs,
        batch_size=TRAIN.batch_size,
        weight_decay=TRAIN.weight_decay,
        checkpoint_dir=PATHS.checkpoints_dir,
        checkpoint_name="best_model.npz",
        seed=TRAIN.seed,
        verbose=True,  # real-time epoch logs
    )

    print("[Train] Start training...")
    history = trainer.fit()

    # Keep only the best checkpoint file in checkpoints/.
    best_path = PATHS.checkpoints_dir / "best_model.npz"
    for ckpt in PATHS.checkpoints_dir.glob("*.npz"):
        if ckpt.resolve() != best_path.resolve():
            ckpt.unlink(missing_ok=True)

    history_path = save_history(history, PATHS.outputs_dir / "logs")
    print(f"Saved training history: {history_path}")

    plot_training_curves(history, PATHS.outputs_dir / "figures")

    print("[Train] Finished.")
    print(f"[Train] Best checkpoint: {best_path}")


if __name__ == "__main__":
    main()
